models:

  - name: YOLOv8n
    path: models/yolov8n.pt

  - name: YOLO26n
    path: modele/yolo26n.pt

dataset:
  name: visdrone
  path: ../datasets/VisDrone/images/val
  labels: ../datasets/VisDrone/labels/val


settings:
  confidence: 0.5
  image_size: 640